### ISSUE TITLE
Support multiple tablets running Fullykiosk and thus multiple devices

### ISSUE THREAD

**Issue by dsegantx** [cgarwood/homeassistant-fullykiosk#50]
Configuration only allows for one device.  I have 3 tablets in the house.  Would be lovely to be able to leverage all of them into this integration.

**Comment by derandiunddasbo** [comment]
Uhm... I'm wondering why this issue was opened (and even got two thumbs up from other users). 

I'm using this integration with two tablets right now. I have to admit, I don't remember exactly how I configured them initially, but I suspect they were both discovered by the auto discovery...? I can't remember having any issues, when integrating them into HA. Must have been worked out of the box:

![image](https://user-images.githubusercontent.com/15999980/132220047-c0dc908f-ed76-4528-8ae8-05ad6dc4e65b.png)

What exactly did you do and what got you stuck when trying to inegrate the second device?

**Comment by cgarwood** [comment]
Missed the GitHub notification on this originally, but yeah.. this is already possible. Just add the integration again and give it the IP of the next tablet.

**Comment by derandiunddasbo** [comment]
Yeah, you're right, that's it. I just had to add the integration a second time to configure the second tablet. Had no issues with that.

**Comment by dsegantx** [comment]
Clearly it’s not an intuitive behavior.  I certainly am used to auto discovery.  I’ll see about getting the readme updated with this tip.

Thanks for providing it.  OK to close

**Comment by derandiunddasbo** [comment]
While I agree that it would certainly be helpful to mention this in the readme, adding integrations multiple times to add new devices is quite common for HASS integrations. This clearly isn't anything special for the FKB integration.

BTW: Github issues can of couse be closed by the maintainer of a project, but as the opener of an issue you also have the permission to close it.
