### ISSUE TITLE
Camera failed trying to restart

### ISSUE THREAD

**Issue by gamer06** [cgarwood/homeassistant-fullykiosk#52]
Hi,

Today I acquired the license from FB.
I have an Android tablet Samsung Tab A7, in the latest version, with everything updated.
If I enable "Enable Visual Motion Detection" (front camera), the stream from the tablet camera does not work. Always give me this error:
"Camera failed trying to restart" ! in the Fully Kiosk application itself.

At the same time as I use Home Assistant, it gives me this error in the log:
"The camera entity camera.a7_fully does not support requesting width and height, please open an issue with the integration author".

But if you turn off the motion detector and just leave the camera on, the camera works.
Do you have a solution?

**Comment by gamer06** [comment]
Any help?

Thanks!

**Comment by cgarwood** [comment]
Unfortunately I don't think we'll be able to help much here, as this component doesn't currently implement a camera platform. I know some tablets struggle with motion detection enabled because of the amount of CPU it uses. My best guess would be that the tablet doesn't have enough resources to both run motion detection and stream the camera feed at the same time, but I admittedly haven't looked into it much.
